'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

first_num = int(1)
second_num = int(1)
sum_fib_num = int(0)
sum_num = int(0)

while sum_fib_num <= 4000000:
    sum_fib_num = first_num + second_num
    first_num = second_num
    second_num = sum_fib_num
    if sum_fib_num % 2 == 0:
        sum_num += sum_fib_num
print(sum_num)
